export type JSend <T> = {  // reutn get< productListResponse<Product> >(`/product/${id}`) returnerar en product|| // reutn get< productListResponse<ProductList> >(`/product/${id}`) returnerar alla producter
	status: "success"| "fail"| "error"
	data: T// replace with array or single data. Jsend.data
	message?: string // when error return message
}

export type productList = Product[]// array of all the products

export type Product = ProductData & { // complete product
	id: number
	//order_items:  OrderItem[]
}

export type ProductData = {// data from user
	name: string,
    description: string,
    price: number,
    images: {},
    stock_status: string,
    stock_quantity: number,
}

export type productResponse = {
	status: "success"| "fail"| "error"
	data: Product
	message?: string
}


export type orderList = Order[]// array of all the orders

export type Order = orderData & {// aditional data for the order generated by the API. Complete order
  id: number,
  order_total: number
  order_items:  OrderItem[]
}


export type orderData = { // data from the user for the order
	customer_first_name: string,
	customer_last_name: string,
	customer_address: string,
	customer_postcode: number
	customer_city: string
	customer_email: string
	customer_phone?: number
}

export type OrderItem = { // Data of the order item to be added to the order.
  id: number
  qty: number
  item_price: number
  item_total: number
  order:      Order
  order_id:   number
  product:    Product
  product_id: number
}
