

export type JSend <T> = {  // reutn get< productListResponse<Product> >(`/product/${id}`) returnerar en product|| // reutn get< productListResponse<ProductList> >(`/product/${id}`) returnerar alla producter
	status: "success"| "fail"| "error"
	data: T// replace with array or single data. Jsend.data
	message?: string // when error return message
}

export type productList = Product[]// array of all the products

export type Product = ProductData & { // complete product
	id: number
}

export type ProductData = {// data from user
	name: string,
    description: string,
    price: number,
    images: {},
    stock_status: string,
    stock_quantity: number,
}

export type productResponse = {
	status: "success"| "fail"| "error"
	data: Product
	message?: string
}


// array of all the orders

export type Order  = {// aditional data for the order generated by the API. Complete order
  id: number,
  customer_first_name: string,
	customer_last_name: string,
	customer_address: string,
	customer_postcode: string,
	customer_city: string
	customer_email: string
	customer_phone?: string
	order_total: number
    order_items:  []
}


export type orderData  = { // data from clientside
	customer_first_name: string,
	customer_last_name: string,
	customer_address: string,
	customer_postcode: string,
	customer_city: string
	customer_email: string
	customer_phone?: string
	order_total: number
	order_item: []

}


export type OrderItem = { // Data of the order item to be added to the order.
  id: number
  qty: number
  item_price: number
  item_total: number
  order_id:   number
  product_id: number
}

export type orderItemList = OrderItem[]

export type orderList  = Order []
